use serde::{Deserialize, Serialize};
use timebreak_core::{HitboxType, PlayerStance, TargetPose};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DirectionBias {
    Center,
    High,
    Low,
    Left,
    Right,
    HighLeft,
    HighRight,
    LowLeft,
    LowRight,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShotTelemetryEvent {
    pub shot_id: String,
    pub session_id: String,
    pub timestamp_ms: u64,
    pub weapon_id: String,
    pub shot_index: usize,
    pub ammo_before: u32,
    pub target_id: Option<String>,
    pub target_pose: Option<TargetPose>,
    pub target_visible_fraction: Option<f32>,
    pub aim_x: f32,
    pub aim_y: f32,
    pub target_center_x: Option<f32>,
    pub target_center_y: Option<f32>,
    pub head_center_x: Option<f32>,
    pub head_center_y: Option<f32>,
    pub aim_error_x: Option<f32>,
    pub aim_error_y: Option<f32>,
    pub aim_error_distance: Option<f32>,
    pub recoil_x: f32,
    pub recoil_y: f32,
    pub spread_x: f32,
    pub spread_y: f32,
    pub final_shot_x: f32,
    pub final_shot_y: f32,
    pub player_velocity_x: f32,
    pub player_velocity_y: f32,
    pub player_speed: f32,
    pub stance: PlayerStance,
    pub airborne: bool,
    pub scoped: bool,
    pub hit: bool,
    pub hitbox: Option<HitboxType>,
    pub headshot: bool,
    pub reaction_time_ms: Option<u64>,
    pub screen_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionMetrics {
    pub session_id: String,
    pub start_time_ms: u64,
    pub end_time_ms: u64,
    pub duration_seconds: u32,
    pub weapon_id: String,
    pub shots_fired: u32,
    pub hits: u32,
    pub misses: u32,
    pub accuracy: f32,
    pub headshots: u32,
    pub headshot_percentage: f32,
    pub kills: u32,
    pub avg_reaction_time_ms: f32,
    pub median_reaction_time_ms: f32,
    pub p90_reaction_time_ms: f32,
    pub mean_horizontal_error: f32,
    pub mean_vertical_error: f32,
    pub rms_error: f32,
    pub direction_bias: DirectionBias,
    pub movement_score: f32,
    pub spray_score: f32,
    pub overall_score: f32,
    pub moving_shots_percentage: f32,
}
